import React,{useEffect,useMemo,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {BrowserRouter} from 'react-router-dom'
import {Activity,Plane,BatteryCharging,Wrench,ShieldCheck,BrainCircuit,LogOut,MapPin,Gauge,Users,AlertTriangle,CloudSun,FileBarChart,Radio,PlusCircle} from 'lucide-react'
import {api,login,store,User} from './services/api'
import './styles.css'

type KPI={missions_total:number,completion_rate:number,fleet_available:number,maintenance_open:number,avg_battery_soh:number,avg_prediction_energy_wh:number}
const demoAccounts=[['Admin','admin@droneopt.ai','Admin123!'],['Operator','operator@droneopt.ai','Operator123!'],['Technician','tech@droneopt.ai','Tech123!'],['Customer','customer@droneopt.ai','Customer123!']]

function Login({onLogin}:{onLogin:(u:User)=>void}){const [email,setEmail]=useState('admin@droneopt.ai'),[password,setPassword]=useState('Admin123!'),[err,setErr]=useState('');async function go(e:any){e.preventDefault();setErr('');try{onLogin(await login(email,password))}catch(x:any){setErr(x.message)}}return <div className="loginWrap"><div className="hero"><div className="brand"><Plane/> DroneOptAI</div><h1>Energy-aware drone operations, explained.</h1><p>Mission planning, fleet health, AI prediction, explainability and operational decisions in one reference platform.</p><div className="heroStats"><div><b>4</b><span>RBAC roles</span></div><div><b>AI</b><span>Energy prediction</span></div><div><b>XAI</b><span>Traceable decisions</span></div></div></div><form className="loginCard" onSubmit={go}><h2>Sign in</h2><p>Use a demo account below.</p><label>Email<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{err&&<div className="error">{err}</div>}<button>Enter platform</button><div className="accounts">{demoAccounts.map(a=><button type="button" key={a[0]} onClick={()=>{setEmail(a[1]);setPassword(a[2])}}><b>{a[0]}</b><small>{a[1]}</small></button>)}</div></form></div>}
function Metric({icon,title,value,sub}:{icon:any,title:string,value:any,sub:string}){const I=icon;return <div className="metric"><I size={22}/><div><span>{title}</span><strong>{value}</strong><small>{sub}</small></div></div>}
function Panel({title,sub,children,icon}:{title:string,sub?:string,children:any,icon?:any}){const I=icon;return <div className="panel"><div className="panelHead"><div><h2>{title}</h2>{sub&&<p>{sub}</p>}</div>{I&&<I/>}</div>{children}</div>}

function App(){
 const [user,setUser]=useState<User|null>(store.user),[view,setView]=useState('Overview'),[kpi,setKpi]=useState<KPI|null>(null),[missions,setMissions]=useState<any[]>([]),[drones,setDrones]=useState<any[]>([]),[bats,setBats]=useState<any[]>([]),[maint,setMaint]=useState<any[]>([]),[users,setUsers]=useState<any[]>([]),[pred,setPred]=useState<any|null>(null),[history,setHistory]=useState<any[]>([]),[weather,setWeather]=useState<any|null>(null),[telemetry,setTelemetry]=useState<any[]>([]),[report,setReport]=useState<any|null>(null),[err,setErr]=useState(''),[loading,setLoading]=useState(false)
 const [newMission,setNewMission]=useState({origin:'Hub C',destination:'Zone South',distance_km:6.5,payload_kg:1.0,wind_speed_ms:3.0})
 const canOps=!!user&&['admin','operator'].includes(user.role), canFleet=!!user&&['admin','operator','technician'].includes(user.role)
 async function load(){if(!user)return;setLoading(true);setErr('');try{setMissions(await api('/missions'));setWeather(await api('/weather/current').catch(()=>null));if(canFleet){setDrones(await api('/drones'));setBats(await api('/batteries'));setKpi(await api('/kpis'));setMaint(await api('/maintenance').catch(()=>[]))}else{setDrones([]);setBats([]);setKpi(null);setMaint([])}if(user.role==='admin')setUsers(await api('/users'));if(canOps){setHistory(await api('/predictions'));setReport(await api('/reports/summary'))}}catch(e:any){setErr(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[user])
 if(!user)return <Login onLogin={setUser}/>
 const nav=[['Overview',Activity],['Missions',MapPin],...(canFleet?[['Fleet',Plane],['Batteries',BatteryCharging]] as any:[]),...(['admin','operator','technician'].includes(user.role)?[['Maintenance',Wrench]] as any:[]),...(user.role==='admin'?[['Users',Users]] as any:[]),...(canOps?[['AI & XAI',BrainCircuit],['Reports',FileBarChart]] as any:[])]
 async function runPrediction(id:number){setErr('');try{const x=await api(`/missions/${id}/predict`,{method:'POST'});setPred(x);setHistory(await api('/predictions'));setReport(await api('/reports/summary'));setView('AI & XAI')}catch(e:any){setErr(e.message)}}
 async function runWhatIf(m:any){setErr('');try{const x=await api(`/missions/${m.id}/what-if`,{method:'POST',body:JSON.stringify({payload_kg:Math.max(0,m.payload_kg*.8),wind_speed_ms:Math.max(0,m.wind_speed_ms-3)})});setPred(x);setView('AI & XAI')}catch(e:any){setErr(e.message)}}
 async function approve(id:number){await api(`/missions/${id}/approve`,{method:'POST'});await load()}
 async function showTelemetry(id:number){setTelemetry(await api(`/telemetry/${id}`));setView('AI & XAI')}
 async function createMission(e:any){e.preventDefault();const c=weather?.current||{};await api('/missions',{method:'POST',body:JSON.stringify({...newMission,altitude_m:100,planned_speed_ms:11,temperature_c:c.temperature_2m??20,humidity_pct:c.relative_humidity_2m??50})});await load()}
 const latestTelemetry=telemetry[telemetry.length-1]
 return <div className="app"><aside><div className="brand"><Plane/>DroneOptAI</div><nav>{nav.map(([name,I]:any)=><a key={name} className={view===name?'active':''} onClick={()=>setView(name)}><I/>{name}</a>)}</nav><div className="role"><ShieldCheck/><div><small>Signed in as</small><b>{user.role}</b></div></div><button className="logout" onClick={()=>{store.clear();setUser(null)}}><LogOut/> Sign out</button></aside><main><header><div><p className="eyebrow">Operational Analytics Platform</p><h1>{view==='Overview'?`Welcome, ${user.full_name}`:view}</h1></div><span className="status"><i/> {loading?'Refreshing':'System operational'}</span></header>{err&&<div className="error topError">{err}</div>}
 {view==='Overview'&&<><section className="metrics">{kpi?<><Metric icon={MapPin} title="Missions" value={kpi.missions_total} sub={`${kpi.completion_rate}% completion`}/><Metric icon={Plane} title="Available fleet" value={kpi.fleet_available} sub={`${drones.length} drones registered`}/><Metric icon={BatteryCharging} title="Battery health" value={`${kpi.avg_battery_soh}%`} sub="Average SOH"/><Metric icon={Wrench} title="Open maintenance" value={kpi.maintenance_open} sub="Requires attention"/></>:<><Metric icon={MapPin} title="Your missions" value={missions.length} sub="Customer-visible missions"/><Metric icon={ShieldCheck} title="Role" value={user.role} sub="RBAC enforced by API"/></>}</section><section className="grid"><div className="panel wide"><div className="panelHead"><div><h2>Mission control</h2><p>Role-aware mission access and AI-assisted pre-flight assessment.</p></div><span>{missions.length} missions</span></div><MissionTable missions={missions} canOps={canOps} runPrediction={runPrediction} runWhatIf={runWhatIf} approve={approve} showTelemetry={showTelemetry}/></div><Panel title="Live weather" sub="Open-Meteo · demo hub" icon={CloudSun}>{weather?<div className="weather"><strong>{weather.current?.temperature_2m}°C</strong><span>Wind {weather.current?.wind_speed_10m} m/s</span><span>Humidity {weather.current?.relative_humidity_2m}%</span></div>:<div className="empty">Weather unavailable</div>}</Panel>{canFleet&&<Panel title="Fleet health" sub="Aircraft readiness" icon={Gauge}>{drones.map(d=><div className="fleet" key={d.id}><div><Plane/><span><b>{d.serial_number}</b><small>{d.model}</small></span></div><em className={`pill ${d.status}`}>{d.status}</em></div>)}</Panel>}{canFleet&&<Panel title="Battery lifecycle" sub="SOH and replacement risk" icon={BatteryCharging}>{bats.map(b=><div className="battery" key={b.id}><div><b>{b.code}</b><small>{b.charge_cycles} cycles</small></div><div className="bar"><i style={{width:`${b.state_of_health}%`}}/></div><strong>{b.state_of_health}%</strong></div>)}</Panel>}</section></>}
 {view==='Missions'&&<section className="stack"><Panel title="Mission registry" sub="Customers see only their own missions"><MissionTable missions={missions} canOps={canOps} runPrediction={runPrediction} runWhatIf={runWhatIf} approve={approve} showTelemetry={showTelemetry}/></Panel>{['admin','operator','customer'].includes(user.role)&&<Panel title="Create mission" sub="Weather is copied from the current demo-hub reading"><form className="missionForm" onSubmit={createMission}><input value={newMission.origin} onChange={e=>setNewMission({...newMission,origin:e.target.value})}/><input value={newMission.destination} onChange={e=>setNewMission({...newMission,destination:e.target.value})}/><input type="number" step=".1" value={newMission.distance_km} onChange={e=>setNewMission({...newMission,distance_km:+e.target.value})}/><input type="number" step=".1" value={newMission.payload_kg} onChange={e=>setNewMission({...newMission,payload_kg:+e.target.value})}/><input type="number" step=".1" value={newMission.wind_speed_ms} onChange={e=>setNewMission({...newMission,wind_speed_ms:+e.target.value})}/><button><PlusCircle/> Create</button></form></Panel>}</section>}
 {view==='Fleet'&&<Panel title="Fleet" sub="Available to operator, technician and admin">{drones.map(d=><div className="dataRow" key={d.id}><b>{d.serial_number}</b><span>{d.model}</span><span>{d.total_flight_hours} h</span><em className={`pill ${d.status}`}>{d.status}</em></div>)}</Panel>}
 {view==='Batteries'&&<Panel title="Batteries" sub="SOH, cycle count and replacement status">{bats.map(b=><div className="dataRow" key={b.id}><b>{b.code}</b><span>{b.state_of_health}% SOH</span><span>{b.charge_cycles} cycles</span><em className={`pill ${b.status}`}>{b.status}</em></div>)}</Panel>}
 {view==='Maintenance'&&<Panel title="Maintenance" sub="Technician workflow visibility">{maint.map(m=><div className="dataRow" key={m.id}><b>Drone #{m.drone_id}</b><span>{m.category}</span><span>{m.severity}</span><em className={`pill ${m.status}`}>{m.status}</em></div>)}</Panel>}
 {view==='Users'&&<Panel title="Users & roles" sub="Admin-only endpoint">{users.map(u=><div className="dataRow" key={u.id}><b>{u.full_name}</b><span>{u.email}</span><span>{u.role}</span><em className={`pill ${u.active?'available':'maintenance'}`}>{u.active?'active':'disabled'}</em></div>)}</Panel>}
 {view==='AI & XAI'&&<section className="grid"><Panel title="AI decision support" sub="Prediction or what-if result" icon={BrainCircuit}>{pred?<PredictionCard pred={pred}/>:<div className="empty"><BrainCircuit size={44}/><b>No prediction selected</b><p>Run AI from a mission.</p></div>}</Panel><Panel title="Telemetry" sub="Selected mission time series" icon={Radio}>{telemetry.length?<><div className="telemetryStats"><b>{telemetry.length} samples</b><span>Battery {latestTelemetry?.battery_pct?.toFixed(1)}%</span><span>Power {latestTelemetry?.power_w?.toFixed(0)} W</span></div><div className="spark">{telemetry.map((t,i)=><i key={i} style={{height:`${Math.max(8,t.power_w/6)}px`}} title={`${t.power_w} W`}/>)}</div></>:<div className="empty">Choose “Telemetry” on a mission.</div>}</Panel><div className="panel wide"><div className="panelHead"><div><h2>Prediction history</h2><p>Persisted model outputs for traceability</p></div><span>{history.length}</span></div>{history.map(h=><div className="dataRow" key={h.id}><b>Mission #{h.mission_id}</b><span>{h.energy_wh} Wh</span><span>{h.model_version}</span><em className={`pill ${h.risk_level==='low'?'available':h.risk_level==='high'?'maintenance':''}`}>{h.risk_level}</em></div>)}</div></section>}
 {view==='Reports'&&<Panel title="Operational report" sub="Server-generated summary for admin/operator">{report?<div className="reportGrid"><ReportBox title="Missions" value={report.missions.total} sub={`${report.missions.approved} approved · ${report.missions.completed} completed`}/><ReportBox title="Predictions" value={report.predictions.total} sub={`${report.predictions.avg_energy_wh} Wh avg`}/><ReportBox title="Fleet" value={report.fleet.drones} sub={`${report.fleet.available} available`}/><ReportBox title="Battery SOH" value={`${report.fleet.avg_battery_soh}%`} sub={`${report.maintenance_open} open maintenance`}/></div>:<div className="empty">No report data yet.</div>}</Panel>}
 <footer>Reference implementation · DroneOptAI v1.1 · Role: {user.role}</footer></main></div>
}

function MissionTable({missions,canOps,runPrediction,runWhatIf,approve,showTelemetry}:any){return <div className="table"><div className="tr th"><span>Route</span><span>Payload</span><span>Weather</span><span>Status</span><span>Action</span></div>{missions.map((m:any)=><div className="tr" key={m.id}><span><b>{m.origin} → {m.destination}</b><small>{m.distance_km} km · {m.altitude_m} m</small></span><span>{m.payload_kg} kg</span><span>{m.wind_speed_ms} m/s wind</span><span><em className={`pill ${m.status}`}>{m.status}</em></span><span className="actions">{canOps&&<><button className="mini" onClick={()=>runPrediction(m.id)}>Run AI</button><button className="mini ghost" onClick={()=>runWhatIf(m)}>What-if</button>{m.status!=='approved'&&<button className="mini ghost" onClick={()=>approve(m.id)}>Approve</button>}</>}<button className="mini ghost" onClick={()=>showTelemetry(m.id)}>Telemetry</button></span></div>)}</div>}
function PredictionCard({pred}:{pred:any}){return <div className="prediction"><div className={`risk ${pred.risk_level}`}><AlertTriangle/><div><small>Risk</small><b>{pred.risk_level}</b></div></div><div className="predNums"><div><small>Energy</small><b>{pred.energy_wh} Wh</b></div><div><small>Duration</small><b>{pred.duration_min} min</b></div><div><small>Efficiency</small><b>{pred.efficiency_m_per_wh} m/Wh</b></div></div><h3>Recommendation</h3><p>{pred.recommendation}</p><h3>Top factors</h3>{pred.explanation.top_factors.map((f:any)=><div className="factor" key={f[0]}><span>{f[0]}</span><b>{f[1]}</b></div>)}<small className="model">Model: {pred.model_version}</small></div>}
function ReportBox({title,value,sub}:{title:string,value:any,sub:string}){return <div className="reportBox"><small>{title}</small><b>{value}</b><span>{sub}</span></div>}

createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><App/></BrowserRouter></React.StrictMode>)
